#
# Дириктория docker-compose.yml
#

version: '2'
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # слева указан порт который займет nginx в локальной ОС, справа указан дефолтный порт на котором nginx работает в контейнере
        ports:
            - "8000:80"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # образ nginx будет общаться с php (имеет зависимость)
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # образ PHP будет общаться с mysql (имеет зависимость)
        links:
            - mysql
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./www:/var/www
    mysql:
        # образ mysql из dockerhub-хранилища
        image: mysql
        # слева указан порт который займет mysql в локальной ОС, справа указан дефолтный порт на котором mysql работает в контейнере
        ports:
            - "3306:3306"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
    pma:
        # используем последний стабильный образ phpmyadmin
        image: phpmyadmin/phpmyadmin
        # сообщаем контейнеру о перезапуске, если система перезагружается
        restart: always
        # образ phpmyadmin будет общаться с mysql (имеет зависимость)
        links:
            - mysql:mysql
        # слева указан порт который займет pma в локальной ОС, справа указан дефолтный порт на котором pma работает в контейнере
        ports:
            - 8183:80
        # прописываем название нашего MySQL хоста, логин и пароль
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret